grafana:
  sidecar:
    datasources:
      defaultDatasourceEnabled: false
  additionalDataSources:
    - name: prometheus
      type: prometheus
      url: http://prometheus-kube-prometheus-prometheus:9090/
      access: proxy
      isDefault: true
