{{- if .Values.certificateChange }}
apiVersion: v1
kind: Secret
metadata:
  name: linkerd-trust-anchor
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  tls.crt: |-
    {{ .Files.Get "certs/linkerd-trust-anchor.crt" | b64enc }}
  tls.key: |-
    {{ .Files.Get "certs/linkerd-trust-anchor.key"  | b64enc }}
{{- end }}