apiVersion: v1
kind: Secret
metadata:
  name: linkerd-trust-anchor
type: Opaque
data:
  tls.crt: |-
    {{ .Files.Get "rootCA/ca.crt" | b64enc }}
  tls.key: |-
    {{ .Files.Get "rootCA/ca.key"  | b64enc }}