{{- if .Values.certificateChange }}
{{ $crt := .Files.Get "certs/webhook-issuer-tls.crt" | b64enc }}
{{ $key := .Files.Get "certs/webhook-issuer-tls.key"  | b64enc }}
{{- range .Values.namespaces -}}
apiVersion: v1
kind: Secret
metadata:
  name: webhook-issuer-tls
  namespace: {{ . }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  tls.crt: |-
    {{ $crt }}
  tls.key: |-
    {{ $key }}
---
{{- end }}    
{{- end }}