apiVersion: v1
kind: Secret
metadata:
  name: webhook-issuer-tls
type: Opaque
data:
  tls.crt: |-
    {{ .Files.Get "webhookCA/ca.crt" | b64enc }}
  tls.key: |-
    {{ .Files.Get "webhookCA/ca.key"  | b64enc }}