apiVersion: v1
kind: Secret
metadata:
  annotations:
    cert-utils-operator.redhat-cop.io/injectca-from-secret: linkerd/test1
  name: test-inject-ca
type: kubernetes.io/tls
stringData:
  tls.crt: ""
  tls.key: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    cert-utils-operator.redhat-cop.io/injectca-from-secret: linkerd/test1
  name: test-inject-ca-cm