apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    deploymentName: {{ include "nginx.fullname" . }}
spec:
  scaleTargetRef:
    deploymentName: {{ include "nginx.fullname" . }}
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: access_frequency
      threshold: '3'
      query: sum(rate(request_total[2m]))