# Default values for jmeter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: #{docker-registry-login-server}#/jmeter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: #{limit-cpu}#
    memory: #{limit-memory}#
  requests:
    cpu: #{request-cpu}#
    memory: #{request-memory}#

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 60

nodeSelector: {}

tolerations: 
  - key: "sku"
    operator: "Equal"
    value: "load"
    effect: "NoSchedule"
affinity: {}

influxdb:
  enabled: true
  config:
    graphite:
      enabled: true
      bind_address: 2003
      # database: jmeter
  env:
    - name: INFLUXDB_DB
      value: "jmeter"
  tolerations:
    - key: "sku"
      operator: "Equal"
      value: "load"
      effect: "NoSchedule"
  persistence:
    enabled: true
    storageClass: "managed-premium"
    size: #{influxdb-persistence}#
  resources:
    requests:
      memory: #{influxdb-request-memory}#
      cpu: #{influxdb-request-cpu}#
    limits:
      memory: #{influxdb-limit-memory}#
      cpu: #{influxdb-limit-cpu}#
grafana:
  enabled: true
  adminUser: admin
  adminPassword: #{jmeter_grafana_password}#
  deploymentStrategy:
    type: Recreate
  
  tolerations:
    - key: "sku"
      operator: "Equal"
      value: "load"
      effect: "NoSchedule"
  
  dashboardsConfigMaps:
    default: "jmeter-dashboard" 
     
  persistence:
    enabled: true
    storageClass: "managed-premium"
    size: #{grafana-persistence}#

  resources:
    requests:
      memory: #{grafana-request-memory}#
      cpu: #{grafana-request-cpu}#
    limits:
      memory: #{grafana-limit-memory}#
      cpu: #{grafana-limit-cpu}#
  ingress:
    enabled: true    
    annotations: 
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/rewrite-target: /
    path: /
    hosts:
      - #{service-ingress-name}#-#{domain_url}#
  grafana.ini:
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
    server:
      root_url: https://#{service-ingress-name}#-#{domain_url}#
    auth.generic_oauth:
      enabled: true
      allow_sign_up: true
      team_ids:
      allowed_organizations:
      name: Auth0
      client_id: #{auth0_client_id}#
      client_secret: #{auth0_client_secret}#
      scopes: openid profile email
      auth_url: https://#{auth0_domain_raw_url}#/authorize
      token_url: https://#{auth0_domain_raw_url}#/oauth/token
      api_url: https://#{auth0_domain_raw_url}#/userinfo

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: jmeter-influxdb
          type: influxdb
          #This should be tempalte base on Release.name but this would be support in helm version 3 with Lua.
          #This value should be changed http://{{Release.name}}-influxdb:8086
          url: "http://jmeter-influxdb:8086"
          database: "jmeter"
          access: proxy
          isDefault: true