---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap
  namespace: linkerd-viz
spec:
  secretName: tap-k8s-tls
  duration: {{.Values.certificate.webhook.duration}}
  renewBefore: {{.Values.certificate.webhook.renewBefore}}
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: tap.linkerd-viz.svc
  dnsNames:
  - tap.linkerd-viz.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-tap-injector
  namespace: linkerd-viz
spec:
  secretName: tap-injector-k8s-tls
  duration: {{.Values.certificate.webhook.duration}}
  renewBefore: {{.Values.certificate.webhook.renewBefore}}
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: tap-injector.linkerd.svc
  dnsNames:
  - tap-injector.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth