apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knife.fullname" . }}
  labels:
    {{- include "knife.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "knife.selectorLabels" . | nindent 6 }}
  template:
    metadata:    
      annotations:
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        rollme: {{ randAlphaNum 5 | quote }}
    {{- end }} 
        checksum/config: {{ include (print $.Template.BasePath "/scripts-cm.yaml") . | sha256sum }}   
      labels:
        {{- include "knife.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "knife.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          livenessProbe:
            exec:
              command:
              - cat
              - /dev/null
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
              - cat
              - /dev/null
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:  
          {{ range $path, $bytes := .Files.Glob ( printf "scripts/**") }}
          {{ $name := base $path }}
            - name: cm-multi-file-volume
              mountPath: {{ printf "/scripts/%s/%s" (index (regexSplit "scripts" (dir $path) -1) 1) $name | indent 2 }}
              subPath: {{- sha256sum (printf "%s/%s" (index (regexSplit "scripts" (dir $path) -1) 1 ) $name ) | indent 2 }}
          {{ end }}     
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cm-multi-file-volume
          configMap:
            name: {{ include "knife.fullname" . }}-scripts