{{ if .Values.rbac.role.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "knife.fullname" . }}
  labels:
{{- include "knife.labels" . | nindent 4 }}
  annotations:    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: list-pods
  apiGroup: ""
subjects:
- kind: ServiceAccount
  name: {{ include "knife.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}