apiVersion: v1
kind: Service
metadata:
  name: google
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ExternalName
  externalName: cap-cst-dummy-plt-dev-api.azurewebsites.net
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: google
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/upstream-vhost: "cap-cst-dummy-plt-dev-api.azurewebsites.net"
spec:
  rules:
  - host: test-dummy-plt-dev.conduent-cap.com
    http:
      paths:
      - path: /
        backend:
          serviceName: google
          servicePort: 80