kind: Service
apiVersion: v1
metadata:
  name: google
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ExternalName
  externalName: www.google.cl

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: proxy-assets-ingress
  annotations:
    ingress.kubernetes.io/configuration-snippet: |
      # we cannot pass Host header
      set $best_http_host "";
      proxy_set_header Host                   $best_http_host;

spec:
  rules:
  - host: test-dummy-plt-dev.conduent-cap.com
    http:
      paths:
      - path: /
        backend:
          serviceName: google
          servicePort: 80